#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# model_free_build.sh — build the FoundationPose model-free representation.
#
#     ./scripts/model_free_build.sh [--model cylinder5] [--force]
#
# Runs the OFFICIAL upstream Neural Object Field stage
# (`bundlesdf/run_nerf.py::run_one_ob`) over a reference set generated by
#
#     ./scripts/run_isaac_task.sh <log> 1800 \
#         simulators/isaac/generate_model_free_references.py
#
# A BATCH JOB, NOT A WORKER REQUEST. The build takes minutes and writes into the
# reference directory, so it runs as its own container with that directory
# mounted read-write rather than through the long-lived worker, whose mounts are
# deliberately read-only.
#
# CACHED ON THE INPUTS THAT CAN CHANGE THE ANSWER. The representation is rebuilt
# only when one of these moves:
#
#     the reference-set content digest      (any view, mask, pose or K)
#     the pinned FoundationPose revision    (a different estimator)
#     the model-free configuration digest   (upstream's config_ycbv.yml)
#
# so a stale representation cannot be silently reused, and an unchanged one is
# not rebuilt for every pose estimate.
#
# NO CAD IS PASSED. The container receives the reference directory and nothing
# else; there is no mesh argument, and the meshes live on a mount this job does
# not request.
# ---------------------------------------------------------------------------
set -u
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE="${WISEPACK_FP_IMAGE:-wisepack-foundationpose:pinned}"
MODEL="cylinder5"
FORCE=0

while [ $# -gt 0 ]; do
    case "$1" in
        --model) MODEL="$2"; shift 2 ;;
        --force) FORCE=1; shift ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

ROOT="$REPO/.cache-perception/model-free/$MODEL"
BASE="$ROOT/reference/ob_0000001"
MANIFEST="$BASE/wisepack_reference_manifest.json"

if [ ! -f "$MANIFEST" ]; then
    echo "[model-free] ERROR: no reference set at $BASE" >&2
    echo "[model-free]        generate one first:" >&2
    echo "[model-free]        ./scripts/run_isaac_task.sh /tmp/refs.log 1800 \\" >&2
    echo "[model-free]            simulators/isaac/generate_model_free_references.py" >&2
    exit 1
fi

if ! docker image inspect "$IMAGE" >/dev/null 2>&1; then
    echo "[model-free] ERROR: $IMAGE does not exist — build it first:" >&2
    echo "[model-free]        ./scripts/setup_foundationpose.sh" >&2
    exit 1
fi

# --- the cache key ----------------------------------------------------------
# THE VALUES ARE EXTRACTED BY PATTERN, not by position. The image prints an
# NVIDIA licence banner to stdout before anything the command produces, and
# `tr -d '\n'` happily folded that banner into the cache key — which then
# changed on nothing and named a directory containing the licence text.
REF_DIGEST="$(python3 -c "import json,sys; print(json.load(open('$MANIFEST'))['reference_set_digest'])")"
FP_REV="$(docker run --rm "$IMAGE" cat /opt/foundationpose.revision 2>/dev/null \
          | grep -oE '^[0-9a-f]{40}$' | head -1)"
CFG_DIGEST="$(docker run --rm "$IMAGE" sha256sum /opt/foundationpose/bundlesdf/config_ycbv.yml 2>/dev/null \
              | grep -oE '^[0-9a-f]{64}' | head -1 | cut -c1-16)"
if [ -z "$FP_REV" ] || [ -z "$CFG_DIGEST" ]; then
    echo "[model-free] ERROR: could not read the FoundationPose revision or the" >&2
    echo "[model-free]        model-free config digest from $IMAGE." >&2
    exit 1
fi
KEY="${REF_DIGEST}_${FP_REV:0:12}_${CFG_DIGEST}"
STAMP="$ROOT/representation/$KEY"
REPORT="$STAMP/build_report.json"

echo "[model-free] object            : $MODEL"
echo "[model-free] reference set     : $BASE"
echo "[model-free] reference digest  : $REF_DIGEST"
echo "[model-free] foundationpose    : $FP_REV"
echo "[model-free] config digest     : $CFG_DIGEST"
echo "[model-free] cache key         : $KEY"

if [ -f "$REPORT" ] && [ "$FORCE" = "0" ]; then
    echo "[model-free] representation is already built for this key — reusing it."
    echo "[model-free] report: $REPORT"
    echo "[model-free]        (--force rebuilds)"
    exit 0
fi

mkdir -p "$STAMP"

# THE REFERENCE DIRECTORY IS THE ONLY DATA MOUNT, and it is the only thing the
# job is given. `/datasets` — where the CAD meshes live — is deliberately NOT
# mounted here: a model-free build that could open a mesh would be one bug away
# from using it.
# THE SAME GPU ANSWER THE WORKER USES. This host has no NVIDIA Container
# Toolkit, so `--gpus all` is rejected by the daemon; the shared library probes
# and returns the verified fallback. A build that quietly fell back to the CPU
# would take hours and look like a slow GPU rather than a missing one.
. "$REPO/scripts/lib_foundationpose_gpu.sh"
GPU_ARGS=()
if ! foundationpose_gpu_args GPU_ARGS; then
    echo "[model-free] ERROR: no GPU is reachable from a container on this host." >&2
    echo "[model-free]        The Neural Object Field needs one; refusing to" >&2
    echo "[model-free]        start a build that would run on the CPU." >&2
    exit 1
fi

echo "[model-free] building the Neural Object Field (upstream run_one_ob)..."
docker run --rm "${GPU_ARGS[@]}" \
    -v "$ROOT:/model-free" \
    -v "$REPO/perception/foundationpose/model_free_build.py:/tmp/build.py:ro" \
    -e PYTHONPATH=/opt/foundationpose:/opt/foundationpose/bundlesdf:/opt/foundationpose/mycpp/build \
    "$IMAGE" \
    python /tmp/build.py \
        --base-dir /model-free/reference/ob_0000001 \
        --out /model-free/representation/$KEY/build_report.json
STATUS=$?

# SUCCESS IS THE ARTEFACT, NOT THE EXIT CODE — and that is not leniency.
#
# The upstream stack segfaults during interpreter shutdown (`free(): invalid
# pointer`, exit 139) AFTER the mesh, the texture and the report have been
# written and after the completion marker has been printed. It is an OpenGL/
# OSMesa teardown crash in a process that has already finished its work, and
# judging the build by that exit code threw away a completed reconstruction.
#
# So the test is: did the job SAY it finished, and are the artefacts there. A
# crash before the marker still fails, because neither condition holds. The
# teardown crash is REPORTED rather than swallowed, so it stays visible.
if [ ! -f "$REPORT" ]; then
    echo "[model-free] BUILD FAILED (exit $STATUS, no report written)" >&2
    exit "${STATUS:-1}"
fi
if [ "$STATUS" -ne 0 ]; then
    echo "[model-free] NOTE: the container exited $STATUS AFTER writing its"
    echo "[model-free]       artefacts — an upstream teardown crash in the GL"
    echo "[model-free]       stack, not a build failure. Artefacts verified below."
fi

python3 - "$REPORT" "$REF_DIGEST" "$FP_REV" "$CFG_DIGEST" <<'PY'
import json, sys
report_path, ref_digest, fp_rev, cfg_digest = sys.argv[1:5]
with open(report_path, encoding="utf-8") as handle:
    report = json.load(handle)
# THE KEY IS RECORDED IN THE ARTEFACT, not only in its path: a report that
# cannot say which inputs produced it is not evidence about them.
report.update({"reference_set_digest": ref_digest,
               "foundationpose_revision": fp_rev,
               "model_free_config_digest": cfg_digest})
with open(report_path, "w", encoding="utf-8") as handle:
    json.dump(report, handle, indent=2)
print(f"[model-free] built in {report['build_seconds']}s")
print(f"[model-free]   mesh        {report['mesh_path']}")
print(f"[model-free]   vertices    {report['vertices']:,}  faces {report['faces']:,}")
print(f"[model-free]   principal   {report['principal_length_m']*1000:.1f} mm")
print(f"[model-free]   transverse  {report['transverse_diameter_m']*1000:.1f} mm")
PY

echo "[model-free] report: $REPORT"
